services:
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    team.db:
        container_name: team.db
        environment:
            SA_PASSWORD: "Test1234"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1433:1433"

    appointment.db:
        container_name: appointment.db
        environment:
            SA_PASSWORD: "Test1234"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1434:1433"

    team.api:
        container_name: team.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:9000
            - "ConnectionStrings__TeamConnectionString=Server=team.db;Database=TeamDb;User Id=sa;Password=Test1234;Encrypt=False;"
            - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
        depends_on:
            - team.db
            - rabbitmq
        ports:
            - "9000:80"

    appointment.api:
        container_name: appointment.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:9001
            - "ConnectionStrings__AppointmentConnectionString=Server=appointment.db;Database=AppointmentDb;User Id=sa;Password=Test1234;Encrypt=False;"
            - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
        depends_on:
            - appointment.db
            - rabbitmq
        ports:
            - "9001:80"

    ocelotapigw:
        container_name: ocelotapigw
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - team.api
            - appointment.api
        ports:
            - "9010:80"
